language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2.3
  - ruby-head

sudo: false


before_install:
  - 'gem install bundler'

before_script:
  - 'bundle exec rake install:local'

script:
  - 'shopt -s globstar && ruby test/**/*_test.rb'
